# 빌드 스테이지
FROM alpine:3.14 AS build
LABEL maintainer="soonge679@gmail.com"

# 필요한 패키지 설치 및 Tomcat 다운로드
RUN apk add --no-cache wget tar openjdk8-jre-base && \
    wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz -O /tmp/apache-tomcat.tar.gz && \
    mkdir -p /usr/local/tomcat && \
    tar -xzf /tmp/apache-tomcat.tar.gz -C /usr/local/tomcat --strip-components=1 && \
    rm /tmp/apache-tomcat.tar.gz

# 최종 이미지 스테이지
FROM alpine:3.14

# 필요한 패키지 설치
RUN apk add --no-cache openjdk8-jre-base && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone && \
    apk del --purge tzdata && \
    rm -rf /var/cache/apk/*

# Tomcat 복사
COPY --from=build /usr/local/tomcat /usr/local/tomcat

# MariaDB JDBC 드라이버 복사
COPY mariadb-java-client-3.4.0.jar /usr/local/tomcat/lib

# Tomcat 포트 노출
EXPOSE 8080

# Tomcat 실행
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
