apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      role: slave
  template:
    metadata:
      labels:
        app: mariadb
        role: slave
    spec:
      nodeSelector:
        type: db
      containers:
      - image: soonge97/db-slave:v1.9
        name: slave
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: store
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 200Mi
            cpu: 200m
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 1
          successThreshold: 1           
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        volumeMounts:
        - name: db-storage
          mountPath: /mnt/data/db
      volumes:
      - name: db-storage
        hostPath:
          path: /mnt/data/db-slave
          type: DirectoryOrCreate
