# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml

---
apiVersion: metallb.io/v1beta1 
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.31.46.220-172.31.46.230
  autoAssign: true

--- 
apiVersion: metallb.io/v1beta1 
kind: L2Advertisement 
metadata:
  name: l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
